# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
#   username: postgres
#   password: password

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 3306
  username: root

# development:
#   <<: *default
#   host: 127.0.0.1
#   password: ''
#   database: equills_dev

development:
  <<: *default
  database: equills_dev
  # adapter: sqlite3
  # database: db/equills_dev.sqlite3

production:
  <<: *default
  database: letrismo_production
  password: <%= ENV['db_password'] %>