development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/equills_dev.sqlite3

test:
  adapter: sqlite3
  database: db/equills_test.sqlite3
  pool: 5
  timeout: 5000

production:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  encoding: utf8mb4
  adapter: mysql2
  timeout: 5000
  port: 3306
  database: letrismo_production
  password: <%= ENV['db_password'] %>